/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "buttons": {
        "reg": string;
    };
    "phrases": {
        "start": string;
        "reg": {
            "name": string;
            "age": string;
        };
    };
    "commands": {
        "start": string;
        "reg": string;
    };
    "languages": {
        "en": string;
        "ru": string;
    };
    "scenes": {
        "reg": {
            "welcome": string;
            "name": string;
            "age": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
